using System.ComponentModel.DataAnnotations;

namespace ProjetoCRM.API.Dtos.Client
{
    public class AddClientDto
    {
        //DTO to POST client to the clinic. Id not necessary, it will be generated by SQL Server.

        [MaxLength(100)]
        [Required(ErrorMessage = "Por favor, insira um valor para o nome")]
        public string? Name { get; set; }

        [MaxLength(14)]
        [Required(ErrorMessage = "Por favor, insira um valor para o CPF")]
        [RegularExpression(@"^\d{3}\.\d{3}\.\d{3}-\d{2}$", ErrorMessage = "O CPF deve estar no formato xxx.xxx.xxx-xx")]
        public string? Cpf { get; set; }

        [Required(ErrorMessage = "Por favor, insira um valor para o endereço")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "Por favor, insira um valor para o e-mail")]
        [EmailAddress(ErrorMessage = "Por favor, insira um endereço de e-mail válido")]
        public string? Email { get; set; }
    }
}
